---
- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: 'Install Apt packages'
  apt: name={{item}} state=installed
  with_items:
       - libavahi-compat-libdnssd-dev
       - cmake
       - liblockdev1-dev
       - libudev-dev
       - libxrandr-dev
       - python-dev
       - swig
       - git

- name: 'Git clone LibCEC Platform'
  git: repo=git://github.com/Pulse-Eight/platform.git dest=/tmp/platform accept_hostkey=yes

- name: 'Git clone LibCEC library'
  git: repo=git://github.com/Pulse-Eight/libcec.git dest=/tmp/libcec accept_hostkey=yes

- name: 'Make build directories for LibCEC'
  command: "{{item}}"
  with_items:
       - mkdir -p /tmp/platform/build
       - mkdir -p /tmp/libcec/build

- name: 'Make Install Platform library'
  command: "{{item}} chdir=/tmp/platform/build"
  with_items:
       - cmake ..
       - make
       - make install

- name: 'Make Install LibCEC library'
  command: "{{item}} chdir=/tmp/libcec/build"
  with_items:
       - cmake -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib ..
       - make -j4
       - make install 
       - ldconfig

- name: 'Remove legacy nodejs'
  apt: name=nodejs-legacy state=absent

- name: 'Download latest nodejs'
  get_url: url=http://node-arm.herokuapp.com/node_latest_armhf.deb dest=/tmp/node_latest_armhf.deb mode=0600

- name: 'Install lastest node'
  apt: deb=/tmp/node_latest_armhf.deb state=present

- name: 'Install Homebridge + Plugins'
  npm: name={{item}} global=yes
  with_items:
       - homebridge

- name: 'Copy Homebridge default config ~/.homebridge'
  copy: src='includes/.homebridge/config.json' dest='/home/pi/.homebridge/'

- name: 'Copy Homebridge default config ~/.homebridge'
  copy: src='includes/.homebridge/config.json' dest='/home/pi/.homebridge/'

- name: 'Copy Homebridge init script to /etc/init.d'
  copy: src='includes/etc/init.d/homebridge' dest='/etc/init.d/' mode=0755

- name: 'Set homebridge to init on boot'
  command: update-rc.d homebridge defaults

- name: 'Enable hdmi_force_hotplug'
  replace:
    dest=/boot/config.txt
    regexp='#hdmi_force_hotplug=1'
    replace='hdmi_force_hotplug=1'
    backup=no

- name: 'Disable HDMI CEC switch to PI on boot'
  lineinfile: 
    dest=/boot/config.txt
    line="hdmi_ignore_cec_init=1"
    state=present
